backend/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Lexik\Bundle\JWTAuthenticationBundle\Security\User\JWTUserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Attribute\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'Cette adresse mail est déjà associée à un compte')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, JWTUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['articles.index', 'user.message', 'message.chat'])]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    #[Groups(['articles.index', 'user.message', 'message.chat'])]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100, nullable: true)]
    #[Groups(['articles.index', 'user.message', 'message.chat'])]
    private ?string $firstName = null;

    #[ORM\Column(length: 100, nullable: true)]
    #[Groups(['articles.index', 'user.message', 'message.chat'])]
    private ?string $lastName = null;

    #[ORM\Column]
    #[Groups(['articles.index', 'user.message', 'message.chat'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?bool $isVerified = null;

    /**
     * @var Collection<int, ArticleLike>
     */
    #[ORM\OneToMany(targetEntity: ArticleLike::class, mappedBy: 'author', orphanRemoval: true)]
    private Collection $articleLikes;

    /**
     * @var Collection<int, ArticleRating>
     */
    #[ORM\OneToMany(targetEntity: ArticleRating::class, mappedBy: 'author', orphanRemoval: true)]
    private Collection $articleRatings;

    /**
     * @var Collection<int, Article>
     */
    #[ORM\OneToMany(targetEntity: Article::class, mappedBy: 'author')]
    private Collection $articles;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'sender', orphanRemoval: true)]
    private Collection $sendedMessages;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'receiver', orphanRemoval: true)]
    private Collection $receivedMessages;

    public function __construct()
    {
        $this->articleLikes = new ArrayCollection();
        $this->articleRatings = new ArrayCollection();
        $this->articles = new ArrayCollection();
        $this->sendedMessages = new ArrayCollection();
        $this->receivedMessages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getFullName(): string
    {
        if ($this->firstName && $this->lastName) {
            return $this->firstName . ' ' . $this->lastName;
        }
        return $this->email;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function isVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, ArticleLike>
     */
    public function getArticleLikes(): Collection
    {
        return $this->articleLikes;
    }

    public function addArticleLike(ArticleLike $articleLike): static
    {
        if (!$this->articleLikes->contains($articleLike)) {
            $this->articleLikes->add($articleLike);
            $articleLike->setAuthor($this);
        }

        return $this;
    }

    public function removeArticleLike(ArticleLike $articleLike): static
    {
        if ($this->articleLikes->removeElement($articleLike)) {
            // set the owning side to null (unless already changed)
            if ($articleLike->getAuthor() === $this) {
                $articleLike->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ArticleRating>
     */
    public function getArticleRatings(): Collection
    {
        return $this->articleRatings;
    }

    public function addArticleRating(ArticleRating $articleRating): static
    {
        if (!$this->articleRatings->contains($articleRating)) {
            $this->articleRatings->add($articleRating);
            $articleRating->setAuthor($this);
        }

        return $this;
    }

    public function removeArticleRating(ArticleRating $articleRating): static
    {
        if ($this->articleRatings->removeElement($articleRating)) {
            // set the owning side to null (unless already changed)
            if ($articleRating->getAuthor() === $this) {
                $articleRating->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setAuthor($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getAuthor() === $this) {
                $article->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getSendedMessages(): Collection
    {
        return $this->sendedMessages;
    }

    public function addSendedMessage(Message $sendedMessage): static
    {
        if (!$this->sendedMessages->contains($sendedMessage)) {
            $this->sendedMessages->add($sendedMessage);
            $sendedMessage->setSender($this);
        }

        return $this;
    }

    public function removeSendedMessage(Message $sendedMessage): static
    {
        if ($this->sendedMessages->removeElement($sendedMessage)) {
            // set the owning side to null (unless already changed)
            if ($sendedMessage->getSender() === $this) {
                $sendedMessage->setSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getReceivedMessages(): Collection
    {
        return $this->receivedMessages;
    }

    public function addReceivedMessage(Message $receivedMessage): static
    {
        if (!$this->receivedMessages->contains($receivedMessage)) {
            $this->receivedMessages->add($receivedMessage);
            $receivedMessage->setReceiver($this);
        }

        return $this;
    }

    public function removeReceivedMessage(Message $receivedMessage): static
    {
        if ($this->receivedMessages->removeElement($receivedMessage)) {
            // set the owning side to null (unless already changed)
            if ($receivedMessage->getReceiver() === $this) {
                $receivedMessage->setReceiver(null);
            }
        }

        return $this;
    }

    public static function createFromPayload($id, array $payload): User
    {
        return (new User())
            ->setId($id)
            ->setEmail($payload['email'] ?? null)
            ->setRoles($payload['roles']);
    }

backend/src/Form/ProfileForm.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;

class ProfileForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, [
                'attr' => [
                    'placeholder' => 'exemple@domaine.com'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => "Veuillez entrer une adresse email",
                    ]),
                    new Email([
                        'message' => "L'adresse email n'est pas valide",
                    ])
                ]
            ])
            ->add('firstName', TextType::class, [
                'label' => 'Prénom',
                'required' => false,
                'attr' => [
                    'placeholder' => 'Votre prénom'
                ]
            ])
            ->add('lastName', TextType::class, [
                'label' => 'Nom',
                'required' => false,
                'attr' => [
                    'placeholder' => 'Votre nom'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

backend/src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Form\ProfileForm;
use App\Form\UpdatePasswordForm;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route("/profile")]
#[IsGranted("ROLE_USER")]
final class ProfileController extends AbstractController
{
    #[Route('', name: 'app_profile', methods: ['GET', 'POST'])]
    public function index(
        Request $request,
        UserRepository $userRepository,
        EntityManagerInterface $entityManager
    ): Response {
        $user = $userRepository->findUserByEmail($this->getUser()->getUserIdentifier());
        $form = $this->createForm(ProfileForm::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();
            $this->addFlash('success', 'Votre profil a été mis à jour avec succès.');
            return $this->redirectToRoute('app_profile');
        }
        return $this->render('profile/index.html.twig', [
            'profileForm' => $form
        ]);
    }

    #[Route('/change-password', name: 'app_profile_change_password', methods: ['GET', 'POST'])]
    public function changePassword(
        Request $request,
        UserPasswordHasherInterface $passwordHasher,
        UserRepository $userRepository
    ): Response {
        $form = $this->createForm(UpdatePasswordForm::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $userRepository->findUserByEmail($this->getUser()->getUserIdentifier());
            if (!$passwordHasher->isPasswordValid(
                $user,
                $form->get("currentPassword")->getData()
            )) {
                $this->addFlash('error', 'Le mot de passe actuel est incorrect.');
                return $this->redirectToRoute('app_profile_change_password');
            }
            $userRepository->upgradePassword(
                $user,
                $passwordHasher
                    ->hashPassword($user, $form->get("plainPassword")->getData())
            );
            $this->addFlash('success', 'Votre mot de passe a été modifié avec succès.');
            return $this->redirectToRoute('app_profile');
        }
        return $this->render('profile/change_password.html.twig', [
            'updatePasswordForm' => $form
        ]);
    }
}

backend/templates/profile/_change_password_form.html.twig
{{ form_start(updatePasswordForm, {
	'attr': {
		'class' : "card-body"
	}
}) }}
	{{ form_row(updatePasswordForm.currentPassword) }}
	{{ form_row(updatePasswordForm.plainPassword) }}
	<div class="col-12 text-end">
		<button class="btn btn-primary mb-0">Changer mon mot de passe</button>
	</div>
{{ form_end(updatePasswordForm) }}

backend/templates/profile/_edit_form.html.twig
{{ form_start(profileForm, {
	'attr': {
		'class' : "row g-3"
	}
}) }}
	{{ form_row(profileForm.email) }}
	{{ form_row(profileForm.firstName, {
		'row_attr': {
			'class': "col-md-6"
		}
	}) }}
	{{ form_row(profileForm.lastName, {
		'row_attr': {
			'class': "col-md-6"
		}
	}) }}
	<div class="col-12 text-end">
		<button class="btn btn-primary mb-0">Enregistrer les modifications</button>
	</div>
{{ form_end(profileForm) }}

backend/templates/profile/_profile_card.html.twig
<div class="card-body p-3">
	<div class="text-center mb-3">
		<div class="mb-2">
			<img class="rounded-circle border border-2 border-white" src="/images/profile_image.jpg" alt="">
		</div>
		<h6 class="mb-0">{{ app.user.fullName }}</h6>
		<a href="mailto:{{ app.user.email }}" class="text-reset text-primary-hover small">{{ app.user.email }}</a>
		<hr>
		<ul class="list-group">
			<li class="list-group-item">
				<span class="fw-bold">Nom: </span>
				{{ app.user.lastName|default('Non renseigné') }}
			</li>
			<li class="list-group-item">
				<span class="fw-bold">Prénom: </span>
				{{ app.user.firstName|default('Non renseigné') }}
			</li>
			<li class="list-group-item">
				<span class="fw-bold">Inscrit le: </span>
				{{ app.user.createdAt|date('d M Y') }}
			</li>
			<li class="list-group-item">
				<span class="fw-bold">Roles: </span>
				{% if 'ROLE_ADMIN' in app.user.roles %}
					Administrateur
				{% else %}
					Utilisateur
				{% endif %}
			</li>
			<li class="list-group-item">
				<span class="fw-bold">Status: </span>
				{% if app.user.isVerified %}
					<span class="badge text-bg-success">Email vérifié</span>
				{% else %}
					<span class="badge text-bg-danger">Email non vérifié</span>
				{% endif %}
			</li>
		</ul>
		<hr>
		<ul class="nav nav-pills flex-column">
			<li class="nav-item">
				<a class="nav-link {% if app.request.attributes.get('_route') == 'app_profile' %}active{% endif %}" href="{{ path('app_profile') }}">
					<i class="fa-regular fa-user"></i>
					Mon profile
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link {% if app.request.attributes.get('_route') == 'app_profile_change_password' %}active{% endif %}" href="{{ path('app_profile_change_password') }}">
					Changer mon mot de passe
				</a>
			</li>
		</ul>
	</div>
</div>

backend/templates/profile/change_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Profile
{% endblock %}

{% block body %}
	<section class="pt-3">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-xl-3">
					<div class="offcanvas-lg offcanvas-end" tabindex="-1" id="offcanvasSidebar">
						<div class="offcanvas-header justify-content-end pb-2">
							<button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#offcanvasSidebar" aria-label="Close"></button>
						</div>
						<div class="offcanvas-body p-3 p-lg-0">
							<div class="card bg-light w-100">
								{% include "profile/_profile_card.html.twig" %}
							</div>
						</div>
					</div>
				</div>

				<div class="col-lg-8 col-xl-9">
					<div class="d-grid mb-0 d-lg-none w-100">
						<button class="btn btn-primary mb-4" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasSidebar" aria-controls="offcanvasSidebar">
							<i class="fa-solid fa-bars"></i>
							Menu
						</button>
					</div>

					<div class="vstack gap-4">
						<div class="card border">
							<div class="card-header border-bottom">
								<h4 class="card-header-title">Update Password</h4>
							</div>
							{% include "profile/_change_password_form.html.twig" %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

backend/templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Profile
{% endblock %}

{% block body %}
	<section class="pt-3">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-xl-3">
					<div class="offcanvas-lg offcanvas-end" tabindex="-1" id="offcanvasSidebar">
						<div class="offcanvas-header justify-content-end pb-2">
							<button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#offcanvasSidebar" aria-label="Close"></button>
						</div>
						<div class="offcanvas-body p-3 p-lg-0">
							<div class="card bg-light w-100">
								{% include "profile/_profile_card.html.twig" %}
							</div>
						</div>
					</div>
				</div>

				<div class="col-lg-8 col-xl-9">
					<div class="d-grid mb-0 d-lg-none w-100">
						<button class="btn btn-primary mb-4" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasSidebar" aria-controls="offcanvasSidebar">
							<i class="fa-solid fa-bars"></i>
							Menu
						</button>
					</div>

					<div class="vstack gap-4">
						<div class="card border">
							<div class="card-header border-bottom">
								<h4 class="card-header-title">Informations personnelles</h4>
							</div>

							<div class="card-body">
								{% include "profile/_edit_form.html.twig" %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock %}